// <auto-generated />
namespace TrafficAvoider.Providers.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tripTimes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tripTimes));
        
        string IMigrationMetadata.Id
        {
            get { return "201507261254297_tripTimes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
